### ISSUE TITLE
Hashcat Mask File Support

### ISSUE THREAD

**Issue by tiahgar** [ctxis/crackerjack#15]
Currently the GUI allows users to manually select and create a mask for brute-force attacks on hashes. It would be nice if the user has the option to select [Hashcat mask files](https://hashcat.net/wiki/doku.php?id=mask_attack#hashcat_mask_files) instead.

**Comment by tiahgar** [comment]
Fyi, I already started on some implementation: [15-hashcat-mask-file-support](https://github.com/tiahgar/crackerjack/tree/15-hashcat-mask-file-support).

**Comment by sadreck** [comment]
Looking forward to the pull request - thanks!

**Comment by sadreck** [comment]
I've merged the PR and have put a small fix for users that are upgrading from an older version, so that the settings would fallback to the manual mask.

@tiahgar thank you for your great work!

**Comment by tiahgar** [comment]
Thanks man, you too!
