### ISSUE TITLE
Bug: LDAP doesn't set simple mode properly

### ISSUE THREAD

**Issue by tautology0** [ctxis/crackerjack#19]
In lib/base/ldap.py it's meant to set the LDAP mode to either SIMPLE or NTLM. It fails to set it to simple as there's a wee typo in line 269:
`auth_type = ldap3.SIMPLE if self.auth_type == self.AUTH_METHOD_SIMPLE else ldap3.NTLM`

It should be self._auth_type. i.e.:
`auth_type = ldap3.SIMPLE if self._auth_type == self.AUTH_METHOD_SIMPLE else ldap3.NTLM`

**Comment by sadreck** [comment]
That should actually work, because it's accessing `auth_type` as a property https://github.com/ctxis/crackerjack/blob/5d605a1f988b5f36d58b1675db4a42f127816ead/app/lib/base/ldap.py#L33-L39

If it's not working for you, perhaps there's another issue elsewhere?

**Comment by sadreck** [comment]
I'll close this ticket, but if it's an actual issue please open it again.
