### ISSUE TITLE
Status not updated to finished when using hashkiller-dict

### ISSUE THREAD

**Issue by ramondunker** [ctxis/crackerjack#22]
Hi,

For some reason the status in the dashboard doesn't change to 'Finished' when a large wordlist like hashkiller-dict (https://hashkiller.io/download) is used. This is also the case when a ruleset is used which has invalid rules, like OneRuleToRuleThemAll (https://raw.githubusercontent.com/NotSoSecure/password_cracking_rules/master/OneRuleToRuleThemAll.rule). I've tried looking into why it isn't working but I couldn't find it unfortunately.

**Comment by sadreck** [comment]
Hi,

When you are using a wordlist for the first time, hashcat has to parse it first which can take a bit of a time.

If you want to see the exact error or why it's not working (for debugging), there's a `Files` tab on the left when you are viewing the session. From there you can download the console output files.

Let me know how it goes!

**Comment by ramondunker** [comment]
Hi,

That's the weird thing, there's no error. The hashcat status also shows 'Exhausted', which should set the status of the session to 'Finished' right? I'm only experiencing this with the hashkiller-dict or with rulesets that have faulty lines in them.

Last hashcat status update from screen.log:
```
[s]tatus [p]ause [b]ypass [c]heckpoint [f]inish [q]uit => 
                                                          
Session..........: 1_admin_t2LK_10
Status...........: Exhausted
Hash.Mode........: 1000 (NTLM)
Hash.Target......: /opt/crackerjack/data/sessions/1/10/hashes.txt
Time.Started.....: Wed May 11 14:58:16 2022 (1 min, 22 secs)
Time.Estimated...: Wed May 11 14:59:38 2022 (0 secs)
Kernel.Feature...: Optimized Kernel
Guess.Base.......: File (/opt/wordlists/hashkiller-dict.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:  3272.6 kH/s (0.33ms) @ Accel:1024 Loops:1 Thr:32 Vec:1
Recovered........: 97/979 (9.91%) Digests
Progress.........: 266518036/266518036 (100.00%)
Rejected.........: 1211123/266518036 (0.45%)
Restore.Point....: 266518036/266518036 (100.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidate.Engine.: Device Generator
Candidates.#1....: river888 -> †‰Z×^
Hardware.Mon.#1..: Temp: 44c Util: 89% Core:1590MHz Mem:5000MHz Bus:16
Started: Wed May 11 14:58:11 2022
[2K
Stopped: Wed May 11 14:59:40 2022
$ 
```

**Comment by sadreck** [comment]
Yeah, this is strange. So it appears to be finishing normally but doesn't parse it as finished.

So if you run it with any other wordlists/rules, it runs just fine? And can you upload a screenshot of how it looks in the GUI when the session when it's "unfinished" please?

**Comment by sadreck** [comment]
I'll close this ticket, but if it's still an issue please open it again.
