### ISSUE TITLE
Could not find any devices. Check manually if hashcat -I returns your installed GPUs.

### ISSUE THREAD

**Issue by kdbaranov** [ctxis/crackerjack#24]
Hi. 
This message showing in the web GUI after clean installation. 
![image](https://user-images.githubusercontent.com/96531122/185156530-6d093860-a100-4b4c-bfc4-7890e6ec6968.png)

Hashcat and crackerjack installed on virtual machine running Ubuntu 20.04
Other information.
GPU Nvidia Tesla T4.
Drivers tested NVIDIA-Linux-x86_64-515.48.07, NVIDIA-Linux-x86_64-460.73.01
Current driver NVIDIA-Linux-x86_64-460.73.01

hashcat -I returns 

> root@hashcat1:/home/user# hashcat -I
> hashcat (v5.1.0) starting...
> 
> OpenCL Info:
> 
> Platform ID #1
>   Vendor  : NVIDIA Corporation
>   Name    : NVIDIA CUDA
>   Version : OpenCL 1.2 CUDA 11.2.162
> 
>   Device ID #1
>     Type           : GPU
>     Vendor ID      : 32
>     Vendor         : NVIDIA Corporation
>     Name           : Tesla T4
>     Version        : OpenCL 1.2 CUDA
>     Processor(s)   : 40
>     Clock          : 1590
>     Memory         : 3777/15109 MB allocatable
>     OpenCL Version : OpenCL C 1.2
>     Driver Version : 460.73.01
> 
> Platform ID #2
>   Vendor  : The pocl project
>   Name    : Portable Computing Language
>   Version : OpenCL 1.2 pocl 1.4, None+Asserts, LLVM 9.0.1, RELOC, SLEEF, DISTRO, POCL_DEBUG
> 
>   Device ID #2
>     Type           : CPU
>     Vendor ID      : 128
>     Vendor         : GenuineIntel
>     Name           : pthread-Intel(R) Xeon(R) Gold 6238R CPU @ 2.20GHz
>     Version        : OpenCL 1.2 pocl HSTR: pthread-x86_64-pc-linux-gnu-cascadelake
>     Processor(s)   : 4
>     Clock          : 2194
>     Memory         : 8192/30065 MB allocatable
>     OpenCL Version : OpenCL C 1.2 pocl
>     Driver Version : 1.4

What could it be?

**Comment by sadreck** [comment]
Your hashcat version is quite old (v5.1.0) - I don't think I've even tested this functionality with that version.

Please update to the latest and greatest version (clone the hashcat repo and compile), then update the "hashcat path" in CrackerJack's settings, and it should work.

**Comment by kdbaranov** [comment]
Thanks alot! 
Update helped.

**Comment by sadreck** [comment]
Excellent, glad that worked!
