### ISSUE TITLE
Supported for hashcat 6.2.6 latest

### ISSUE THREAD

**Issue by tautology0** [ctxis/crackerjack#34]
We needed some of the newer hashtypes, so I ended up updating hashcat, which needed some changes to crackerjack. The latest hashcat v6.2.6-851-g6716447df uses a reduced `--help`, but adds `-hh` to dump all hashtypes. It also changed the capitialisation of "Hash Modes"; so I had to make the following changes to app/lib/hashcat/manager.py::

in function get_supported_hashes:
```
output = self.shell.execute([self.hashcat_binary, '-hh'], user_id=0, log_to_db=False)
```

in function __parse_supported_hashes:
```
if line == '- [ Hash Modes ] -':
```

**Comment by sadreck** [comment]
Hi,

I've already fixed this in the same commit as https://github.com/ctxis/crackerjack/issues/32:

https://github.com/sadreck/crackerjack/blob/13321188174a9bac0f3dff49cc7d5df058206d94/app/lib/hashcat/manager.py#L16

And

https://github.com/sadreck/crackerjack/blob/13321188174a9bac0f3dff49cc7d5df058206d94/app/lib/hashcat/manager.py#L73

Let me know if those work!

**Comment by tautology0** [comment]
That's what you get for manually patching only the essential files ;-)
