### ISSUE TITLE
Could not install: Referrer header is missing

### ISSUE THREAD

**Issue by tautology0** [ctxis/crackerjack#5]
A straight install on a clean Ubuntu box lead to the above error when trying to set up an admin user. Looks like it's to do with Flask's CSRF protection having WTF_CSRF_SSL_STRICT applied by default (which is mostly superfluous in the wonderful world of CORS).

Adding the below line to app/__init__.py fixed it:
`app.config['WTF_CSRF_SSL_STRICT'] = False`

**Comment by sadreck** [comment]
Could you provide some extra details for your setup please?

* Which version of Ubuntu are you using (I assume it's Ubuntu based on your other issue raised at #5)?
* Did you install manually or via the ansible scripts?
  * Can you check that the system service is running properly via `sudo systemctl status crackerjack`?
* What is the domain you've configured CrackerJack to run on? Is it an IP, or a domain like `crackerjack.local` or something similar?

**Comment by tautology0** [comment]
That was on my dev machine - moving to production on Debian 10 and I get the same problem.

It was installed manually. 

Crackerjack runs on 127.0.0.1:8080. Nginx runs on a fully qualified name with hostname and domain.

**Comment by sadreck** [comment]
Pushed a fix, thanks for reporting it
