### ISSUE TITLE
Lack of internal logging

### ISSUE THREAD

**Issue by tautology0** [ctxis/crackerjack#6]
I'm getting a 500 error whenever I go to the home page; but there's nowt in any of the nginx error or access logs. If I run crackerjack manually through flask it all works perfectly. It would be nice to have a log I can look at to debug this.

**Comment by sadreck** [comment]
In a terminal window can you run `tail -f /var/log/syslog` and then refresh the CrackerJack page? You should see the error trace there.

Could you also provide the following details please:
* Which version of Ubuntu are you using (I assume it's Ubuntu based on your other issue raised at #5)?
* Did you install manually or via the ansible scripts?
  * Can you check that the system service is running properly via `sudo systemctl status crackerjack`?
* What is the domain you've configured CrackerJack to run on? Is it an IP, or a domain like `crackerjack.local` or something similar?

**Comment by tautology0** [comment]
Aha! /var/log/syslog has all the errors in it. The ultimate problem was that I didn't have the which utility installed.
