### ISSUE TITLE
Weirdness with subprocess.run

### ISSUE THREAD

**Issue by tautology0** [ctxis/crackerjack#7]
For some reason if subprocess.run() uses just the name of the executable it will ignore the path return "not found" when run as part of crackerjack (I can't replicate this from interactive Python3). This is used in several places with "which", "ps", "screen" etc. This problem can be fixed by expanding the command to use a full path.

The user it runs as has a shell of /sbin/nologin.

On a separate note: you really should shell out to do these sort of things, e.g. psutil should be used instead of shelling out to ps.

**Comment by sadreck** [comment]
Regarding `psutil` I think that's a good point, thanks.

I _think_ I know why it doesn't work - the environment variables aren't loaded. You mentioned in #5 that you are using Debian 10, so perhaps this following file is empty?

https://github.com/ctxis/crackerjack/blob/6920304d3a5a97a236a9e6db7e7f16470d0d3869/setup/ansible/roles/service/templates/ubuntu/systemd.j2#L9

I've only tested this with Ubuntu up to 18.04.

**Comment by tautology0** [comment]
I managed to fix it by altering the PATH variable in crackerjack.service. /etc/environment was empty as you guessed!

**Comment by sadreck** [comment]
I think if you set that path to `/etc/profile` it should work just fine!
