### ISSUE TITLE
Pound sign not counted as a special character

### ISSUE THREAD

**Issue by tautology0** [ctxis/crackerjack#8]
Tried to add a user with a £ sign in the password, it was rejected as not being complex enough.

This is because you're using string.punctuation which only has 7-bit US ASCII punctuation characters in it.

**Comment by sadreck** [comment]
Ah, I assumed that everyone in the industry used `hunter2` as their password - my bad!

**Comment by tautology0** [comment]
How did you know my password?

**Comment by sadreck** [comment]
I pushed a fix, should be working as expected now. Thanks for reporting it!
